services:
  ollama:
    image: ghcr.io/zerocluster/ollama
    # depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    command: run

    # secrets:
    #   - { source: ollama_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: ollama, target: /root/.ollama }

    build: .

# secrets:
#   ollama_env.yaml: { file: env.yaml }

networks:
  network: ~

volumes:
  ollama: ~
